# Generated by Django 4.0.3 on 2022-05-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanagementsytem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
