# Generated by Django 4.0.3 on 2022-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanagementsytem', '0004_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('gallerytitle', models.CharField(max_length=100)),
            ],
        ),
    ]
