# Generated by Django 4.0.3 on 2022-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanagementsytem', '0005_tourgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='packagedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pics')),
                ('destinationtitle', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
