# Generated by Django 4.0.3 on 2022-05-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanagementsytem', '0006_packagedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packagedetail',
        ),
    ]
